[hexdiff]
src.git = "https://github.com/ahroach/hexdiff"
fetch.github = "ahroach/hexdiff"

[catpuccin-bat]
src.git = "https://github.com/catppuccin/bat"
fetch.github = "catppuccin/bat"

[flameshot]
src.git = "https://github.com/flameshot-org/flameshot"
fetch.github = "flameshot-org/flameshot"

[mujmap]
src.git = "https://github.com/elizagamedev/mujmap"
fetch.github = "elizagamedev/mujmap"
cargo_locks = [ "Cargo.lock" ]

[nu-scripts]
src.git = "https://github.com/nushell/nu_scripts"
fetch.github = "nushell/nu_scripts"

[swaylock]
src.git = "https://github.com/swaywm/swaylock"
fetch.github = "swaywm/swaylock"

[wezterm-nightly]
src.git = "https://github.com/wez/wezterm"
fetch.github = "wez/wezterm"
git.fetchSubmodules = true
cargo_locks = [ "Cargo.lock" ]

[zsh-alias-tips]
src.git = "https://github.com/djui/alias-tips"
fetch.github = "djui/alias-tips"

[zsh-calc]
src.git = "https://github.com/arzzen/calc.plugin.zsh"
fetch.github = "arzzen/calc.plugin.zsh"

[zsh-git-prompt-useremail]
src.git = "https://github.com/mroth/git-prompt-useremail"
fetch.github = "mroth/git-prompt-useremail"

[zsh-fast-syntax-highlighting]
src.github_tag = "zdharma-continuum/fast-syntax-highlighting"
fetch.github = "zdharma-continuum/fast-syntax-highlighting"
