[hexdiff]
src.git = "https://github.com/ahroach/hexdiff"
fetch.github = "ahroach/hexdiff"

[catpuccin-bat]
src.git = "https://github.com/catppuccin/bat"
fetch.github = "catppuccin/bat"

[zsh-alias-tips]
src.git = "https://github.com/djui/alias-tips"
fetch.github = "djui/alias-tips"

[zsh-calc]
src.git = "https://github.com/arzzen/calc.plugin.zsh"
fetch.github = "arzzen/calc.plugin.zsh"

[zsh-git-prompt-useremail]
src.git = "https://github.com/mroth/git-prompt-useremail"
fetch.github = "mroth/git-prompt-useremail"

[zsh-fast-syntax-highlighting]
src.github_tag = "zdharma-continuum/fast-syntax-highlighting"
fetch.github = "zdharma-continuum/fast-syntax-highlighting"
