# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  age-plugin-yubikey = {
    pname = "age-plugin-yubikey";
    version = "f34c534e8479e4c50095a98f48941d079bd179a3";
    src = fetchFromGitHub ({
      owner = "str4d";
      repo = "age-plugin-yubikey";
      rev = "f34c534e8479e4c50095a98f48941d079bd179a3";
      fetchSubmodules = false;
      sha256 = "sha256-lV8Cw3W3MSThZIhtaUMId50hZswEIIxMUmUiVIUfYFE=";
    });
    date = "2023-01-03";
  };
  hexdiff = {
    pname = "hexdiff";
    version = "3e96f27e65167c619ede35ab04232163dc273e69";
    src = fetchFromGitHub ({
      owner = "ahroach";
      repo = "hexdiff";
      rev = "3e96f27e65167c619ede35ab04232163dc273e69";
      fetchSubmodules = false;
      sha256 = "sha256-G6Qi7e4o+0ahcslJ8UfJrdoc8NNkY+nl6kyDlkJCo9I=";
    });
    date = "2018-01-24";
  };
  zsh-alias-tips = {
    pname = "zsh-alias-tips";
    version = "4d2cf6f10e5080f3273be06b9801e1fd1f25d28d";
    src = fetchFromGitHub ({
      owner = "djui";
      repo = "alias-tips";
      rev = "4d2cf6f10e5080f3273be06b9801e1fd1f25d28d";
      fetchSubmodules = false;
      sha256 = "sha256-0N2DCpMraIXtEc7hMp0OBANNuYhHPLqzJ/hrAFcLma8=";
    });
    date = "2022-11-03";
  };
  zsh-calc = {
    pname = "zsh-calc";
    version = "5b4c85977b693c15eb052cde6b5cef0d6610f567";
    src = fetchFromGitHub ({
      owner = "arzzen";
      repo = "calc.plugin.zsh";
      rev = "5b4c85977b693c15eb052cde6b5cef0d6610f567";
      fetchSubmodules = false;
      sha256 = "sha256-N4FBN7iyyiEyZX/opj63D5acA1Oh0YpFXdz83oIOWPE=";
    });
    date = "2021-03-24";
  };
  zsh-fast-syntax-highlighting = {
    pname = "zsh-fast-syntax-highlighting";
    version = "v1.55";
    src = fetchFromGitHub ({
      owner = "zdharma-continuum";
      repo = "fast-syntax-highlighting";
      rev = "v1.55";
      fetchSubmodules = false;
      sha256 = "sha256-DWVFBoICroKaKgByLmDEo4O+xo6eA8YO792g8t8R7kA=";
    });
  };
  zsh-git-prompt-useremail = {
    pname = "zsh-git-prompt-useremail";
    version = "902541b73a23061e6cbeb889e0a7f179a87d047e";
    src = fetchFromGitHub ({
      owner = "mroth";
      repo = "git-prompt-useremail";
      rev = "902541b73a23061e6cbeb889e0a7f179a87d047e";
      fetchSubmodules = false;
      sha256 = "sha256-lTyqIs2OqnWVVG/yMC9KYvI2bLL77SuIX9NsmWUepNg=";
    });
    date = "2017-04-12";
  };
}
