# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  age-plugin-yubikey = {
    pname = "age-plugin-yubikey";
    version = "84830103936b3a59085381e7155480a86575ceca";
    src = fetchFromGitHub ({
      owner = "str4d";
      repo = "age-plugin-yubikey";
      rev = "84830103936b3a59085381e7155480a86575ceca";
      fetchSubmodules = false;
      sha256 = "sha256-2g8WkId7Sy98QjMD4n9h2xTCUQTjk/rnoTba8nU/3bE=";
    });
    date = "2023-01-29";
  };
  catpuccin-bat = {
    pname = "catpuccin-bat";
    version = "ba4d16880d63e656acced2b7d4e034e4a93f74b1";
    src = fetchFromGitHub ({
      owner = "catppuccin";
      repo = "bat";
      rev = "ba4d16880d63e656acced2b7d4e034e4a93f74b1";
      fetchSubmodules = false;
      sha256 = "sha256-6WVKQErGdaqb++oaXnY3i6/GuH2FhTgK0v4TN4Y0Wbw=";
    });
    date = "2022-11-10";
  };
  hexdiff = {
    pname = "hexdiff";
    version = "3e96f27e65167c619ede35ab04232163dc273e69";
    src = fetchFromGitHub ({
      owner = "ahroach";
      repo = "hexdiff";
      rev = "3e96f27e65167c619ede35ab04232163dc273e69";
      fetchSubmodules = false;
      sha256 = "sha256-G6Qi7e4o+0ahcslJ8UfJrdoc8NNkY+nl6kyDlkJCo9I=";
    });
    date = "2018-01-24";
  };
  zsh-alias-tips = {
    pname = "zsh-alias-tips";
    version = "41cb143ccc3b8cc444bf20257276cb43275f65c4";
    src = fetchFromGitHub ({
      owner = "djui";
      repo = "alias-tips";
      rev = "41cb143ccc3b8cc444bf20257276cb43275f65c4";
      fetchSubmodules = false;
      sha256 = "sha256-ZFWrwcwwwSYP5d8k7Lr/hL3WKAZmgn51Q9hYL3bq9vE=";
    });
    date = "2023-01-19";
  };
  zsh-calc = {
    pname = "zsh-calc";
    version = "5b4c85977b693c15eb052cde6b5cef0d6610f567";
    src = fetchFromGitHub ({
      owner = "arzzen";
      repo = "calc.plugin.zsh";
      rev = "5b4c85977b693c15eb052cde6b5cef0d6610f567";
      fetchSubmodules = false;
      sha256 = "sha256-N4FBN7iyyiEyZX/opj63D5acA1Oh0YpFXdz83oIOWPE=";
    });
    date = "2021-03-24";
  };
  zsh-fast-syntax-highlighting = {
    pname = "zsh-fast-syntax-highlighting";
    version = "v1.55";
    src = fetchFromGitHub ({
      owner = "zdharma-continuum";
      repo = "fast-syntax-highlighting";
      rev = "v1.55";
      fetchSubmodules = false;
      sha256 = "sha256-DWVFBoICroKaKgByLmDEo4O+xo6eA8YO792g8t8R7kA=";
    });
  };
  zsh-git-prompt-useremail = {
    pname = "zsh-git-prompt-useremail";
    version = "902541b73a23061e6cbeb889e0a7f179a87d047e";
    src = fetchFromGitHub ({
      owner = "mroth";
      repo = "git-prompt-useremail";
      rev = "902541b73a23061e6cbeb889e0a7f179a87d047e";
      fetchSubmodules = false;
      sha256 = "sha256-lTyqIs2OqnWVVG/yMC9KYvI2bLL77SuIX9NsmWUepNg=";
    });
    date = "2017-04-12";
  };
}
