# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  catpuccin-bat = {
    pname = "catpuccin-bat";
    version = "ba4d16880d63e656acced2b7d4e034e4a93f74b1";
    src = fetchFromGitHub {
      owner = "catppuccin";
      repo = "bat";
      rev = "ba4d16880d63e656acced2b7d4e034e4a93f74b1";
      fetchSubmodules = false;
      sha256 = "sha256-6WVKQErGdaqb++oaXnY3i6/GuH2FhTgK0v4TN4Y0Wbw=";
    };
    date = "2022-11-10";
  };
  hexdiff = {
    pname = "hexdiff";
    version = "3e96f27e65167c619ede35ab04232163dc273e69";
    src = fetchFromGitHub {
      owner = "ahroach";
      repo = "hexdiff";
      rev = "3e96f27e65167c619ede35ab04232163dc273e69";
      fetchSubmodules = false;
      sha256 = "sha256-G6Qi7e4o+0ahcslJ8UfJrdoc8NNkY+nl6kyDlkJCo9I=";
    };
    date = "2018-01-24";
  };
  mujmap = {
    pname = "mujmap";
    version = "5f700af890769185ad99d4aae9f53496bb2aa6f2";
    src = fetchFromGitHub {
      owner = "elizagamedev";
      repo = "mujmap";
      rev = "5f700af890769185ad99d4aae9f53496bb2aa6f2";
      fetchSubmodules = false;
      sha256 = "sha256-mSJ6uyZSaWWdhqiYNcIm7lC6PZZrZ8PSdxfu+s9MZD0=";
    };
    cargoLock."Cargo.lock" = {
      lockFile = ./mujmap-5f700af890769185ad99d4aae9f53496bb2aa6f2/Cargo.lock;
      outputHashes = {
        
      };
    };
    date = "2023-05-15";
  };
  nu-scripts = {
    pname = "nu-scripts";
    version = "ab0d3aaad015ca8ac2c2004d728cc8bac32cda1b";
    src = fetchFromGitHub {
      owner = "nushell";
      repo = "nu_scripts";
      rev = "ab0d3aaad015ca8ac2c2004d728cc8bac32cda1b";
      fetchSubmodules = false;
      sha256 = "sha256-9WpG6XxTKPgL4T4TquBT0JCA2W7FCWgWXwZAf7VYmkE=";
    };
    date = "2023-06-27";
  };
  wezterm-nightly = {
    pname = "wezterm-nightly";
    version = "9a24f61c22eb2216acc4c483afdcee1c235b96fe";
    src = fetchFromGitHub {
      owner = "wez";
      repo = "wezterm";
      rev = "9a24f61c22eb2216acc4c483afdcee1c235b96fe";
      fetchSubmodules = true;
      sha256 = "sha256-fAi1oT5TMC8c2Ir0aaXTJv/HgVSkkf6V7XrdkiFve0M=";
    };
    cargoLock."Cargo.lock" = {
      lockFile = ./wezterm-nightly-9a24f61c22eb2216acc4c483afdcee1c235b96fe/Cargo.lock;
      outputHashes = {
        "xcb-imdkit-0.2.0" = "sha256-QOT9HLlA26DVPUF4ViKH2ckexUsu45KZMdJwoUhW+hA=";
        "image-0.24.5" = "sha256-fTajVwm88OInqCPZerWcSAm1ga46ansQ3EzAmbT58Js=";
      };
    };
    date = "2023-06-22";
  };
  zsh-alias-tips = {
    pname = "zsh-alias-tips";
    version = "41cb143ccc3b8cc444bf20257276cb43275f65c4";
    src = fetchFromGitHub {
      owner = "djui";
      repo = "alias-tips";
      rev = "41cb143ccc3b8cc444bf20257276cb43275f65c4";
      fetchSubmodules = false;
      sha256 = "sha256-ZFWrwcwwwSYP5d8k7Lr/hL3WKAZmgn51Q9hYL3bq9vE=";
    };
    date = "2023-01-19";
  };
  zsh-calc = {
    pname = "zsh-calc";
    version = "5b4c85977b693c15eb052cde6b5cef0d6610f567";
    src = fetchFromGitHub {
      owner = "arzzen";
      repo = "calc.plugin.zsh";
      rev = "5b4c85977b693c15eb052cde6b5cef0d6610f567";
      fetchSubmodules = false;
      sha256 = "sha256-N4FBN7iyyiEyZX/opj63D5acA1Oh0YpFXdz83oIOWPE=";
    };
    date = "2021-03-24";
  };
  zsh-fast-syntax-highlighting = {
    pname = "zsh-fast-syntax-highlighting";
    version = "v1.55";
    src = fetchFromGitHub {
      owner = "zdharma-continuum";
      repo = "fast-syntax-highlighting";
      rev = "v1.55";
      fetchSubmodules = false;
      sha256 = "sha256-DWVFBoICroKaKgByLmDEo4O+xo6eA8YO792g8t8R7kA=";
    };
  };
  zsh-git-prompt-useremail = {
    pname = "zsh-git-prompt-useremail";
    version = "902541b73a23061e6cbeb889e0a7f179a87d047e";
    src = fetchFromGitHub {
      owner = "mroth";
      repo = "git-prompt-useremail";
      rev = "902541b73a23061e6cbeb889e0a7f179a87d047e";
      fetchSubmodules = false;
      sha256 = "sha256-lTyqIs2OqnWVVG/yMC9KYvI2bLL77SuIX9NsmWUepNg=";
    };
    date = "2017-04-12";
  };
}
