# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "nvme" "usbhid" "usb_storage" "sd_mod" "rtsx_pci_sdmmc" ];
  boot.initrd.kernelModules = [ "dm-snapshot" ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/60478c44-8b96-4e06-9f4f-5de08b189da3";
      fsType = "xfs";
    };

  fileSystems."/home" =
    { device = "/dev/disk/by-uuid/eb082cd3-3173-4ebf-b0df-7b6c5ee2169a";
      fsType = "xfs";
    };

  fileSystems."/var/lib/libvirt" =
    { device = "/dev/mapper/vg--tachi-libvirt";
      fsType = "xfs";
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/C097-2C53";
      fsType = "vfat";
    };

  swapDevices =
    [ { device = "/dev/mapper/vg--tachi-swap"; }
    ];

  powerManagement.cpuFreqGovernor = lib.mkDefault "powersave";
}
