# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, ... }:

{
  imports =
    [
      #<nixpkgs/nixos/modules/installer/scan/not-detected.nix>
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "nvme" "rtsx_pci_sdmmc" ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    {
      device = "/dev/mapper/vg00-nix";
      fsType = "xfs";
    };

  fileSystems."/home" =
    {
      device = "/dev/mapper/vg00-nix--home";
      fsType = "xfs";
    };

  fileSystems."/var/lib/libvirt" =
    {
      device = "/dev/mapper/vg00-libvirt";
      fsType = "xfs";
    };

  fileSystems."/srv/storage" =
    {
      device = "/dev/mapper/vg00-storage";
      fsType = "xfs";
    };

  fileSystems."/boot" =
    {
      device = "/dev/disk/by-uuid/BB29-4FCE";
      fsType = "vfat";
    };

  swapDevices =
    [{ device = "/dev/disk/by-uuid/5fed97fe-6c31-4f65-8f54-097816d61c99"; }];

  nix.maxJobs = lib.mkDefault 4;
}
