name: "Build packages on staging"

on:
  repository_dispatch:
    types: [nixpkgs-update]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.4.0
    - uses: cachix/install-nix-action@v16
      with:
        nix_path: nixpkgs=channel:nixos-unstable
    - uses: cachix/cachix-action@v10
      with:
        name: vlaci
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
    - run: nix flake lock --override-input nixpkgs github:vlaci/nixpkgs/staging
    - run: nix run nixpkgs\#just -- build-pkgs

    - name: Repository Dispatch
      uses: peter-evans/repository-dispatch@v2
      with:
        repository: vlaci/nixpkgs
        token: ${{ secrets.REPO_ACCESS_TOKEN }}
        event-type: nixpkgs-update-ok
