name: "Build packages"
on:
  push:
jobs:
  gather-hosts:
    runs-on: ubuntu-latest
    outputs:
      hosts: ${{ steps.hosts.outputs.hosts }}
    steps:
      - uses: actions/checkout@v3
      - uses: cachix/install-nix-action@v18
      - id: hosts
        run: echo hosts=$(nix eval --impure --json --expr  "with builtins.getFlake (toString ./.); builtins.attrNames nixosConfigurations") > $GITHUB_OUTPUT

  build-pkgs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: cachix/install-nix-action@v18
      - uses: cachix/cachix-action@v12
        with:
          name: vlaci
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"
      - run: nix run nixpkgs\#just -- build-pkgs

  build-hosts:
    needs:
      - build-pkgs
      - gather-hosts
    strategy:
      max-parallel: 1
      matrix:
        host: ${{ fromJSON(needs.gather-hosts.outputs.hosts) }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: cachix/install-nix-action@v18
      - uses: cachix/cachix-action@v12
        with:
          name: vlaci
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"
      - run: nix run nixpkgs\#just -- build-host "${{ matrix.host }}"
